services:
  postgresDB:
    image: postgres:latest
    container_name: postgresql
    env_file:
      - ./configs/db.env
    ports:
      - "5432:5432"
    volumes:
      - ./init/schema/000001_init.up.sql:/docker-entrypoint-initdb.d/000001_init.up.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
  app:
    build: .
    image: rest-api-server:latest
    container_name: server
    env_file:
      - ./configs/.env
    ports:
      - "8000:8000"
    depends_on:
      postgresDB:
        condition: service_healthy